### PR TITLE
ci: run Danger on PRs

### PR DESCRIPTION
**Pull request by macklinu**

### CODE REVIEW

**Comment by orta** [comment]
I don't think relative file compilation works ATM, would recommend doing it to the list directory

**Comment by macklinu** [comment]
Sorry @orta, not sure I follow your comment. What do you suggest for next steps?

**Comment by orta** [comment]
run `yarn build`, then refer to the JS files

**Comment by orta** [comment]
Looks good, can probably just make Danger only run on 6 or `node` and you're 👍

**Comment by macklinu** [comment]
I'm just going to build on Node 6 for now on Travis, since 4 and 8 are erroring before any of the useful commands run (build, lint, test, danger). Will come back around and figure out the Node 8 build. Might just drop building on Node 4. 🤷‍♂️

**Pull request merged**
