### PR TITLE
Publish message on Jest tests success

### PR DESCRIPTION
**Pull request by miszo**
This would be nice for the user to get feedback that some tests had passed.

### CODE REVIEW

**Comment by miszo** [comment]
I'll fix build and get back to you.

**Comment by macklinu** [comment]
See #25 - I think we disabled this functionality because we assumed if the CI build was green, that would be enough to communicate that the tests had passed. 

I’m personally ok having this functionality, but it shouldn’t be the default, and should require an option in the `jest()` function to enable it.

**Comment by miszo** [comment]
Sure thing, I'll look into it and get back to you :)
Do you prefer parameter to be a boolean flag  or just message string which if is null then no feedback would be printed on success?

**Comment by macklinu** [comment]
I'm thinking a boolean flag option in the `IPluginConfig` interface, maybe called `showSuccessMessage`? Thoughts?

https://github.com/macklinu/danger-plugin-jest/blob/2ac7519f94812c36489c22cfe0383e87390feda3/src/index.ts#L15-L17

Also, thank you for your contribution! 😄

**Comment by miszo** [comment]
Hey, yeah - that sounds OK to me. I'm working on it 💪

**Comment by miszo** [comment]
I've just run the plugin with `showSuccessMessage = true`, and here's a result.

image

Please let me know if you want to have this turned on here or not.
If it's OK, then don't hesitate to release a new version on npm ;)

**Review by macklinu — APPROVED** [review]
This is awesome - thanks for making this happen! Will deploy a new minor version once the Travis CI build finishes on the master branch. 🎉

**Comment by miszo** [comment]
No problem. It's been a pleasure. Happy to help you with this awesome danger plugin.
Cheers!

**Pull request merged**
